name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Minikube
      run: |
        ssh -i <(echo "${{ secrets.SSH_KEY }}") \
          -o StrictHostKeyChecking=no \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          "cd ~/scdproject && \
          kubectl apply -f deployment.yaml && \
          kubectl rollout status deployment/my-app"
