name: Deploy to Minikube
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4

    # SSH Setup
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/minikube_key
        chmod 600 ~/.ssh/minikube_key
        echo "${{ secrets.SSH_HOST }} $(ssh-keyscan -t ed25519 ${{ secrets.SSH_HOST }} 2>/dev/null)" >> ~/.ssh/known_hosts

    # Deployment
    - name: Deploy Application
      run: |
        ssh -o ConnectTimeout=30 \
            -i ~/.ssh/minikube_key \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd ~/scdproject || exit 1
        kubectl apply -f deployment.yaml
        kubectl rollout status deployment/my-app --timeout=120s
        minikube service list
        EOF

    # Verification
    - name: Verify Deployment
      run: |
        ssh -i ~/.ssh/minikube_key \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "kubectl get pods,svc -o wide && \
            curl -sI $(minikube service my-app-service --url)"
