name: Deploy to Minikube
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/minikube_key
          chmod 600 ~/.ssh/minikube_key
          echo "${{ secrets.SSH_HOST }} $(ssh-keyscan -t ed25519 ${{ secrets.SSH_HOST }} 2>/dev/null)" >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/minikube_key \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "cd ~/scdproject && \
              kubectl apply -f deployment.yaml && \
              kubectl rollout status deployment/my-app"

      - name: Verify Deployment
        run: |
          ssh -i ~/.ssh/minikube_key \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "kubectl get pods,svc -o wide"
